### ISSUE TITLE
Connect API Database

### ISSUE THREAD

**Issue by Fumicode01** [codesydney/taskstech#15]
Connect API Database in Customer Create Form

**Comment by kimchirice** [comment]
we are not far, now we need to post request to the server(backend).

are you comfortable with Async/Await in JavaScript?
 
I guess, for warm-up, maybe go through that resource quickly??
-  [JavaScript Async/Await Explained in 10 minutes](https://tutorialzine.com/2017/07/javascript-async-await-explained)
-  [Mastering Async/Await in Node.js](https://blog.risingstack.com/mastering-async-await-in-nodejs)
-  [Async functions - making promises friendly](https://developers.google.com/web/fundamentals/primers/async-functions)
-  [Async / Await in JavaScript - What, Why and How - Fun Fun Function](https://www.youtube.com/watch?v=568g8hxJJp4)

**Comment by Fumicode01** [comment]
I see.
I will quickly have a look these.

Thank you!

**Comment by kimchirice** [comment]
hi @Fumicode01 did you find anything useful? if there's no outstanding, I reckon  we good to close this issue?

**Comment by Fumicode01** [comment]
Hi @kimchirice, these are looks useful, but I still can not make any progress.
So, I think it is better we close this issue once.
I do it.
