### ISSUE TITLE
BUG: [Sign Up] Cannot Logged In Using Newly Created User

### ISSUE THREAD

**Issue by ettienekorayyi** [codesydney/taskstech#172]
Summary:

[Updated]: Based on my findings, when the user signs up and used an email that exceeds the maximum character length set by the backend, it still creates the new user however it truncates it as shown in screenshot 2.

When a user signs up by using an email that does not exceed the maximum character length, the user gets created and is able to login successfully as shown in screenshot 1.

Screenshot 1:
![image](https://user-images.githubusercontent.com/19362078/219855190-1075e260-d2ef-4063-ab8c-d350055ee06b.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/19362078/219854835-8050b280-08d5-443b-80af-b6a78ff93487.png)

**Comment by davidtaing** [comment]
Hey @ettienekorayyi,
I was curious and had a peek. It looks like the form is submitting a blank body when you try to login.

**Comment by ettienekorayyi** [comment]
Thanks @davidtaing , I will inform Kevin. He handles the backend stuff.

**Comment by davidtaing** [comment]
@ettienekorayyi, just to ask a clarifying question because I think this is a frontend issue. Usually login forms send the `email` and `password` as part of the request body.

Is that how this form is supposed to work as well?
