### ISSUE TITLE
simplify tradie sign up form

### ISSUE THREAD

**Issue by kimchirice** [codesydney/taskstech#26]
## current API
below informaiton is required when creating a new tradie
```json
{
  "email": "string",
  "password": "string",
  "first_name": "string",
  "last_name": "string",
  "description": "string",
  "phone": "string"
}
```

## target 
simplify it.  a user only need to provide _an Email_ and _Password_, all of ther informaiton is optional if possible

```json
{
  "email": "string",
  "password": "string",
}
```

## note
should a user want to add below information to the profile, it should be able to do with Update method 
```json
{  
"first_name": "string",
  "last_name": "string",
  "description": "string",
  "phone": "string"
}

**Comment by Kevinf7** [comment]
I have now made these changes and is now Live on Pythonanyhwere
![image](https://user-images.githubusercontent.com/30205382/127730099-e6b3af96-9e5f-42c7-a841-cea4309a72d5.png)
